---
  - name: update Packages
    hosts: dev
    tasks: 
      - name: yum update
        yum:
          name: '*'
          state: latest
        when: ansible_pkg_mgr == "yum" 
         
      - name: apt update
        apt:
          name: '*'
          state: latest
        when: ansible_pkg_mgr == "apt"